---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git 
  scm: git
  version: "1.13"
  name: clickhouse

- src: https://github.com/ymka08/vector-role.git
  scm: git
  version: "v1.0.0"
  name: vector-role

- src: https://github.com/ymka08/lighthouse-role.git
  scm: git
  version: "v1.0.0"
  name: lighthouse-role
